dataset_name: HAERAE-HUB/QARV-binary-set
model_ckpt: etri-xainlp/llama2-ko-13b-instruct-v1.2
sampling_params:
  temperature: 0.8
  top_p: 0.95
  min_tokens: 20
  max_tokens: 1024
  stop: ["###", "#", "\n\n", "\n"]