dataset_name: HAERAE-HUB/QARV-binary-set
model_ckpt: quantumaikr/llama-2-70b-fb16-korean
sampling_params:
  temperature: 0.8
  top_p: 0.95
  min_tokens: 20
  max_tokens: 1024
  stop: ["###", "#", "\n\n", "\n"]