- 'microsoft/phi-2'
- 'google/gemma-2b'
- 'google/gemma-7b'
- 'meta-llama/Llama-2-7b-hf'
- 'meta-llama/Llama-2-13b-hf'
- 'meta-llama/Llama-2-70b'
- 'meta-llama/Meta-Llama-3-8B'
- 'meta-llama/Meta-Llama-3-70B'
- '01-ai/Yi-6B'
- '01-ai/Yi-34B'
- 'CohereForAI/c4ai-command-r-v01'
- 'CohereForAI/c4ai-command-r-plus'
- 'Qwen/Qwen1.5-1.8B'
- 'Qwen/Qwen1.5-4B'
- 'Qwen/Qwen1.5-7B'
- 'Qwen/Qwen1.5-14B'
- 'Qwen/Qwen1.5-32B'
- 'Qwen/Qwen1.5-72B'
- 'EleutherAI/polyglot-ko-1.3b'
- 'EleutherAI/polyglot-ko-3.8b'
- 'EleutherAI/polyglot-ko-5.8b'
- 'EleutherAI/polyglot-ko-12.8b'
- 'mistralai/Mistral-7B-v0.1'
- 'google/gemma-2b-it'
- 'google/gemma-7b-it'
- 'meta-llama/Llama-2-7b-chat-hf'
- 'meta-llama/Llama-2-13b-chat-hf'
- 'meta-llama/Llama-2-70b-chat'
- 'meta-llama/Meta-Llama-3-8B-Instruct'
- 'meta-llama/Meta-Llama-3-70B-Instruct'
- '01-ai/Yi-6B-Chat'
- '01-ai/Yi-34B-Chat'
- 'Qwen/Qwen1.5-1.8B-Chat'
- 'Qwen/Qwen1.5-4B-Chat'
- 'Qwen/Qwen1.5-7B-Chat'
- 'Qwen/Qwen1.5-14B-Chat'
- 'Qwen/Qwen1.5-32B-Chat'
- 'Qwen/Qwen1.5-72B-Chat'
- 'mistralai/Mistral-7B-Instruct-v0.2'
- 'upstage/SOLAR-10.7B-v1.0'
- 'yanolja/EEVE-Korean-2.8B-v1.0'
- 'beomi/gemma-ko-2b'
- 'beomi/gemma-ko-7b'
- 'beomi/llama-2-ko-7b'
- 'beomi/llama-2-koen-13b'
- 'beomi/llama-2-ko-70b'
- 'beomi/Llama-3-KoEn-8B-preview'
- 'beomi/Yi-Ko-6B'
- 'beomi/Yi-Ko-34B'
- 'yanolja/EEVE-Korean-10.8B-v1.0'
- 'yanolja/EEVE-Korean-Instruct-10.8B-v1.0'
- 'quantumaikr/gemma-2b-it-ko'
- 'quantumaikr/gemma-7b-it-ko'
- 'heegyu/llama-2-ko-7b-chat'
- 'etri-xainlp/llama2-ko-13b-instruct-v1.2'
- 'quantumaikr/llama-2-70b-fb16-korean'
- 'beomi/Llama-3-KoEn-8B-Instruct-preview'
- 'beomi/Llama-3-KoEn-8B-Instruct-preview'
- 'heegyu/polyglot-ko-3.8b-chat'
- 'heegyu/polyglot-ko-5.8b-chat'
- 'nlpai-lab/kullm-polyglot-12.8b-v2'
- 'yanolja/EEVE-Korean-Instruct-10.8B-v1.0'
- 'nlpai-lab/KULLM3'
