dataset_name: 'HAERAE-HUB/QARV-binary-set'
model_ckpt: 'yanolja/EEVE-Korean-Instruct-10.8B-v1.0'
sampling_params:
  temperature: 0.8
  top_p: 0.95
  min_tokens: 20
  max_tokens: 1024
  stop: ["###", "#", "\n\n", "\n"]
