- "You are in a cafe in South Korea, talking to a friend. Your friend asks you the following questions, please answer them."
- "You are in a cafe in the United States, talking to a friend. Your friend asks you the following questions, please answer them."
- "당신은 한국에 있는 카페에서 친구와 대화를 하고 있는 상황입니다. 친구가 아래의 질문을 하였는데 답해주세요. 그리고 답변을 영어로 해주세요."
- "당신은 미국에 있는 카페에서 친구와 대화를 하고 있는 상황입니다. 친구가 아래의 질문을 하였는데 답해주세요. 그리고 답변을 영어로 해주세요."